config/routes.rb
Rails.application.routes.draw do
  resources :members do
    resources :memberships
  end

  root "members#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, allow_blank: true
  validates :phone_number, uniqueness: true, allow_blank: true

  has_many :memberships, dependent: :destroy

  accepts_nested_attributes_for :memberships

  def self.search condition
    self.where(
      "first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR phone_number LIKE ?", 
      "%#{condition}%", 
      "%#{condition}%", 
      "%#{condition}%", 
      "%#{condition}%"
    )
  end

  def has_valid_membership?
    memberships.any?{ |membership| membership.created_at > 1.year.ago }
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member

  validates :fee, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @search = params[:search]
    @members = if @search
      Member.search(@search)
    else
      Member.includes(:memberships).all
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
    @member.memberships.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone_number, :policies_acceptance, memberships_attributes: [:id, :fee])
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_member, only: [:new, :create]
  before_action :set_membership, only: [:destroy]

  # GET /memberships/new
  def new
    @membership = @member.memberships.build
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = @member.memberships.build(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership.member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to member_url(@membership.member), notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    def set_member
      @member = Member.find(params[:member_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:fee)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def membership_icon membership
    if membership
      content_tag(:i, "", class: "fa fa-check")
    else
      content_tag(:i, "", class: "fa fa-times")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Santrovelo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :policies_acceptance %><br>
    <%= f.check_box :policies_acceptance, { checked: 'checked' } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bike Shop Members</h1>

<%= form_tag("/members", method: :get) do |f| %>
  <div class="field">
    <%= text_field_tag :search, @search %>
    <%= submit_tag "Search" %>
  </div>
<% end %>

<%= link_to 'Show All Members', members_path %>
<%= link_to 'New Member', new_member_path %>

<br/><br/>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Valid membership</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.email %></td>
        <td><%= member.phone_number %></td>
        <td><%= membership_icon(member.has_valid_membership?) %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.fields_for :memberships do |membership_form| %>
      <%= membership_form.label :fee, "Membership fee" %><br>
      <%= membership_form.number_field :fee, { min: 0, step: 1 } %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :policies_acceptance %><br>
    <%= f.check_box :policies_acceptance, { checked: 'checked' } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Member info</h2>
<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @member.phone_number %>
</p>

<p>
  <strong>Policies acceptance:</strong>
  <%= @member.policies_acceptance %>
</p>

<p>
  <strong>Valid membership:</strong>
  <%= @member.has_valid_membership? %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

<h2>Membership info</h2>

<%= link_to 'Add Membership', new_member_membership_path(@member) %>

<table>
  <thead>
    <tr>
      <th>Membership fee</th>
      <th>Created at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @member.memberships.each do |membership| %>
      <tr>
        <td>$<%= membership.fee %></td>
        <td><%= membership.created_at %></td>
        <td><%= link_to 'Destroy', member_membership_path(@member, membership), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/memberships/_form.html.erb
<%= form_for([@member, @membership]) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fee %><br>
    <%= f.number_field :fee, { min: 0, step: 1 } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', member_path(@member) %>